title: The First Symposium of Geometry and Statistics, Yanqi Lake Beijing Institute of Mathematical Sciences and Applications
description: Yau Center at Tsinghua University, Tentatively scheduled in July 2023
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
site.github.is_project_page: false
