title: The Second Symposium of Geometry and Statistics in China
description: The Tsinghua Sanya International Mathematics Forum (TSIMF) <br> Sanya December 11 - 13, 2024 (tentatively)
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
site.github.is_project_page: false

markdown: GFM
