title: The First Symposium of Geometry and Statistics in China
description: Yanqi Lake Beijing Institute of Mathematical Sciences and Applications, Yau Center at Tsinghua University <br> July 23 - 25 2023
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
site.github.is_project_page: false
